name: Get affected

on:
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch main
        run: git fetch origin main

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: yarn

      - name: Affected apps
        run: npx nx affected:apps --base=remotes/origin/main

      - name: Affected libs
        run: npx nx affected:libs --base=remotes/origin/main
